# Generated by Django 2.1.7 on 2019-03-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('c', 'company'), ('s', 'student')], default='s', max_length=1),
            preserve_default=False,
        ),
    ]
