# Generated by Django 2.1.7 on 2019-03-12 23:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_faculty', models.CharField(max_length=100)),
                ('internship_period', models.DateTimeField()),
                ('target_study_year', models.IntegerField()),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=200)),
                ('study_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('interests', models.CharField(max_length=1000)),
                ('cv', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('photo', models.CharField(max_length=50)),
                ('internship_period', models.DateTimeField()),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='took_internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.company_internship')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='profile_categories',
        ),
    ]
