# Generated by Django 2.1.7 on 2019-03-18 18:30

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190318_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_internship',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='cv',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='description',
            field=models.TextField(default='a'),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='faculty',
            field=models.CharField(default='a', max_length=200),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='first_name',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='interests',
            field=models.CharField(default='a', max_length=1000),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='internship_period',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 18, 18, 30, 45, 861846), null=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='last_name',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='photo',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='study_year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
