# Generated by Django 2.1.7 on 2019-03-18 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190318_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_internship',
            name='internship_period',
        ),
        migrations.RemoveField(
            model_name='company_internship',
            name='target_study_year',
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='internship_period',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 18, 18, 38, 1, 479784), null=True),
        ),
    ]
