# Generated by Django 2.1.7 on 2019-03-19 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190318_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_internship',
            name='target_faculty',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='internship_period',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 19, 14, 40, 17, 956459), null=True),
        ),
    ]
