# Generated by Django 2.1.7 on 2019-03-22 13:26

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('main', '0009_auto_20190319_1443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='company_internship',
            new_name='company_internships',
        ),
    ]
