# Generated by Django 2.1.7 on 2019-03-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190322_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_internships',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company_internships',
            name='internship_period',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='company_internships',
            name='target_faculty',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company_internships',
            name='target_study_year',
            field=models.IntegerField(),
        ),
    ]
