# Generated by Django 2.1.7 on 2019-03-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190322_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_internships',
            name='student_interests',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
